### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by abedalzain** [StellarKit/stellar-js-utils#1]
I tried to use stellarkit in my project, But it show bellow error. 

```
ReferenceError: window is not defined
    at Object.<anonymous> (D:\api\plugins\stellar-js-utils\dist\build.js:1:447)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\api\plugins\util\stellar-util.js:4:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by sgehrman** [comment]
use the stellarkit-js project for servers.  that lib doesn't have UI components that need a window
